### ISSUE TITLE
Import doesn't work in Blender 4.1 (API changes)

### ISSUE THREAD

**Issue by clamintus** [Sir-Teatei-Moonlight/monado-forge#4]
```
Importing model from: /home/clamintus/Xeno_modding/chr/en/en020512.chr & /home/clamintus/Xeno_modding/chr/en/en020512.wimdo & /home/clamintus/Xeno_modding/chr/en/en020512.wismt
Read 31 bones.
Found 2 mesh headers.
Found 23 bones.
Found 2 materials.
Finished parsing .wimdo file.
Opening model subfile.
Found 2 vertex tables.
Found 2 face tables.
Found 1 weight tables.
Finished reading vertex data.
unknownVDTypes: {29: 4, 32: 4}
Finished reading face data.
Finished processing mesh data.
Found shader chunk of size 49152 (not supported, skipping)
en020512_EN020512_ATAMA: [#########################] 32 / 32
en020512_EN020512_ATAMA_ALP: [#########################] 1 / 1 
en020512_EN020512_ATAMA_NRM: [#########################] 1 / 1 
en020512_EN020512_ATAMA_MTL: [#########################] 1 / 1 
en020512_EN020512_DOU: [#########################] 32 / 32
en020512_EN020512_DOU_NRM: [#########################] 1 / 1 
en020512_temp0000: [#########################] 1 / 1 
Excluding channel B (all pixels 0.0)
Excluding channel A (all pixels 1.0)
en020512_EN020512_ATAMA: [#########################] 32768 / 32768
en020512_EN020512_ATAMA_ALP: [#########################] 8192 / 8192
en020512_EN020512_ATAMA_NRM: [#########################] 65536 / 65536
en020512_EN020512_ATAMA_MTL: [#########################] 8192 / 8192
en020512_EN020512_DOU: [#########################] 8192 / 8192
en020512_EN020512_DOU_NRM: [#########################] 16384 / 16384
en020512_temp0000: [#########################] 2048 / 2048
Excluding channel B (all pixels 0.0)
Excluding channel A (all pixels 1.0)
Finished parsing .wismt file.
Converting processed data into Blender objects.
Traceback (most recent call last):
  File "/usr/share/blender/4.1/scripts/addons/monado_forge/import_ui.py", line 159, in execute
    return import_sar1_skel_and_wimdo_and_wismt(self, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/blender/4.1/scripts/addons/monado_forge/import_funcs_sar1.py", line 1094, in import_sar1_skel_and_wimdo_and_wismt
    return realise_results(wismtResults, os.path.splitext(os.path.basename(absoluteDataPath))[0], self, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/blender/4.1/scripts/addons/monado_forge/import_funcs.py", line 380, in realise_results
    externalArmature = create_armature_from_bones(externalSkeleton,armatureName,pos,rot,boneSize,positionEpsilon,angleEpsilon)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/blender/4.1/scripts/addons/monado_forge/utils.py", line 266, in create_armature_from_bones
    newBone.layers[1] = b.isEndpoint
    ^^^^^^^^^^^^^^
AttributeError: 'EditBone' object has no attribute 'layers'
```

**Comment by Sir-Teatei-Moonlight** [comment]
Okay first I apologise for not seeing this way earlier.

Looks like Blender did [a thing in version 4.0](https://developer.blender.org/docs/release_notes/4.0/upgrading/bone_collections/) that completely changes how bone layers work. Doesn't look too bad, I'll try to have a look.

**Comment by Sir-Teatei-Moonlight** [comment]
Right so *this* is an easy enough fix. However, fixing it reveals a deeper problem in which the entire node tree API was made blatantly worse, so there's not much point in fixing just this.

I'll turn this into a general "make it not blow up in 4.x" issue.

**Comment by Sir-Teatei-Moonlight** [comment]
Okay that wasn't as painful as expected. Version 6.8.0 should work with Blender 4.1.0, and therefore anything in between that and 3.3.1.
